ORG 0000H
	LJMP INIT

; P0 - Czerwone
; P1 - Żółte
; P2 - Zielone
; P3.2 - przycisk pieszego

ORG 00003h
	LJMP USER

ORG 0000Bh
	LJMP TIMI

ORG 0300H
INIT:
	RCOD EQU 01H
	RTLOW EQU 00FH
	RTHIGH EQU 0FFH
	SETCOD EQU 02H
	SETTLOW EQU 07FH
	SETTHIGH EQU 0FFH
	YCOD EQU 03H
	YTLOW EQU 07FH
	YTHIGH EQU 0FFH
	GCOD EQU 04H
	GTLOW EQU 01FH
	GTHIGH EQU 0FFH

	MAXT EQU 0FFH

	STATE EQU 030H
	LIGHT EQU 00H
	DARK EQU 0FFH
	MOV STATE, #RCOD
	MOV P0, #LIGHT
	MOV P1, #DARK
	MOV P2, #DARK
	MOV TL0, #RTLOW
	MOV TH0, #RTHIGH
	SETB TR0			; zacznij liczyć
	SETB IT0			; przerwania na zboczu
	SETB ET0			; maska timera
	SETB EX0			; maska P3.2 (reset)
	SETB PX0			; wysoki priorytet przycisków
	CLR PT0				; niski priorytet timera
	SETB EA				; maska główna
MAIN:	LJMP MAIN

TIMI:	MOV A, STATE
	CJNE A, #RCOD, NRED
	LJMP RED
NRED:	CJNE A, #YCOD, NYEL
	LJMP YEL
NYEL:	CJNE A, #SETCOD, NSET
	LJMP SETL
NSET:	LJMP GRE

; set set state
RED:	MOV STATE, #SETCOD
	MOV P0, #LIGHT
	MOV P1, #LIGHT
	MOV P2, #DARK
	MOV TL0, #SETTLOW
	MOV TH0, #SETTHIGH
	RETI

; set red
YEL:	MOV STATE, #RCOD
	MOV P0, #LIGHT
	MOV P1, #DARK
	MOV P2, #DARK
	MOV TL0, #RTLOW
	MOV TH0, #RTHIGH
	RETI

; set green
SETL:	MOV STATE, #GCOD
	MOV P0, #DARK
	MOV P1, #DARK
	MOV P2, #LIGHT
	MOV TL0, #GTLOW
	MOV TH0, #GTHIGH
	RETI

; set yellow
GRE:	MOV STATE, #YCOD
	MOV P0, #DARK
	MOV P1, #LIGHT
	MOV P2, #DARK
	MOV TL0, #YTLOW
	MOV TH0, #YTHIGH
	RETI

USER:	MOV A, STATE
	CJNE A, #GCOD, ENDU
	MOV TH0, #MAXT
	MOV TL0, #MAXT
ENDU:	RETI

END