ORG 0000H
	LJMP INIT

; P0 - Czerwone
; P1 - Żółte
; P2 - Zielone
; P3.2 - przycisk pieszego

ORG 00003h
	LJMP USER

ORG 0000Bh
	LJMP TIMI

ORG 0300H
INIT:
	RCOD EQU 01H
	RCOUNT EQU 40D
	SETCOD EQU 02H
	SETCOUNT EQU 10D
	YCOD EQU 03H
	YCOUNT EQU 10D
	GCOD EQU 04H
	GCOUNT EQU 50D

	MAXT EQU 0FFH
	LIGHT EQU 00H
	DARK EQU 0FFH

	STATE EQU 030H
	COUNTER EQU 031H

	TLOW EQU 0F2H
	THIGH EQU 0FFH

	MOV STATE, #RCOD
	MOV P0, #LIGHT
	MOV P1, #DARK
	MOV P2, #DARK
	MOV TL0, #TLOW
	MOV TH0, #THIGH
	MOV COUNTER, #RCOUNT
	SETB TR0			; zacznij liczyć
	SETB IT0			; przerwania na zboczu
	SETB ET0			; maska timera
	SETB EX0			; maska P3.2 (reset)
	SETB PX0			; wysoki priorytet przycisków
	CLR PT0				; niski priorytet timera
	SETB EA				; maska główna
MAIN:	LJMP MAIN

TIMI:	MOV TL0, #TLOW
	MOV TH0, #THIGH
	DJNZ COUNTER, ENDU
STATE:	MOV A, STATE
	CJNE A, #RCOD, NRED
	LJMP RED
NRED:	CJNE A, #YCOD, NYEL
	LJMP YEL
NYEL:	CJNE A, #SETCOD, NSET
	LJMP SETL
NSET:	LJMP GRE

; set set state
RED:	MOV STATE, #SETCOD
	MOV P0, #LIGHT
	MOV P1, #LIGHT
	MOV P2, #DARK
	MOV COUNTER, #SETCOUNT
	RETI

; set red
YEL:	MOV STATE, #RCOD
	MOV P0, #LIGHT
	MOV P1, #DARK
	MOV P2, #DARK
	MOV COUNTER, #RCOUNT
	RETI

; set green
SETL:	MOV STATE, #GCOD
	MOV P0, #DARK
	MOV P1, #DARK
	MOV P2, #LIGHT
	MOV COUNTER, #GCOUNT
	RETI

; set yellow
GRE:	MOV STATE, #YCOD
	MOV P0, #DARK
	MOV P1, #LIGHT
	MOV P2, #DARK
	MOV COUNTER, #YCOUNT
	RETI

USER:	MOV A, STATE
	CJNE A, #GCOD, ENDU
	MOV COUNTER, #01H
	MOV TH0, #MAXT
	MOV TL0, #MAXT
ENDU:	RETI

END